language: android
android:
  components:
    - build-tools-20.0.0
    - android-10
  licenses:
    - 'android-sdk-.*'
    - '.*intel.+'
script:
  - ./gradlew build
notifications:
  email:
    - akiggund@thoughtworks.com
